//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace OrderHub.IntegrationTests.Clients.OrderApi.V1.Contracts
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IOrderApiV1Client
    {
        /// <summary>
        /// Get a full order by id.
        /// </summary>
        /// <remarks>
        /// GET a order (with full content) by order id AND common org id.
        /// </remarks>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetFullOrderResponse>> GetFullOrderAsync(string orderId, string storeId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get a full order by id.
        /// </summary>
        /// <remarks>
        /// GET a order (with full content) by order id AND common org id.
        /// </remarks>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetFullOrderResponse>> GetFullOrderAsync(string orderId, string storeId, System.Threading.CancellationToken cancellationToken);

        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<PaginatedResponseOfGetOrderResponse>> GetOrdersAsync(string storeId, string customerId, int? page, int? pageSize);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<PaginatedResponseOfGetOrderResponse>> GetOrdersAsync(string storeId, string customerId, int? page, int? pageSize, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Get order content by encoded S3 key.
        /// </summary>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetOrderFullContentResponse>> GetOrderContentAsync(string key);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get order content by encoded S3 key.
        /// </summary>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetOrderFullContentResponse>> GetOrderContentAsync(string key, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Get a full order by id.
        /// </summary>
        /// <remarks>
        /// GET a order (with full content) by order id AND common org id.
        /// </remarks>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetFullOrderResponse>> DemoGetFullOrderAsync(string orderId, string storeId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get a full order by id.
        /// </summary>
        /// <remarks>
        /// GET a order (with full content) by order id AND common org id.
        /// </remarks>
        /// <returns>OK</returns>
        /// <exception cref="OrderApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HttpResponse<GetFullOrderResponse>> DemoGetFullOrderAsync(string orderId, string storeId, System.Threading.CancellationToken cancellationToken);

    }

    /// <summary>
    /// Represents metadata for an attachment in a order response.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LineItemInfoResponse
    {
        /// <summary>
        /// Unique GUID identifier for the attachment.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("attachmentId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ItemId { get; set; } = default!;

        /// <summary>
        /// Original filename from the attachment upload.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("filename", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ItemName { get; set; } = default!;

        /// <summary>
        /// MIME type of the attachment (e.g., application/pdf, image/png).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contentType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ContentType { get; set; } = default!;

        /// <summary>
        /// S3 presigned GET URL for downloading the attachment binary content.
        /// <br/>Valid for at least 1 day after returned.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("presignedUrl", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string PresignedUrl { get; set; } = default!;

    }

    /// <summary>
    /// Represents metadata about the content of a order, including media references and content length metrics.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderMetadata
    {
        /// <summary>
        /// A list of media identifiers associated with the order content.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("mediaIds", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string>? MediaIds { get; set; } = default!;

        /// <summary>
        /// The total length of the raw content string in characters.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contentLength", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int ContentLength { get; set; } = default!;

        /// <summary>
        /// The length of visible content after HTML stripping, calculated using text elements for proper multi-byte character handling.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("visibleContentLength", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int VisibleContentLength { get; set; } = default!;

        /// <summary>
        /// The length of plain text content for standard orders. Null for non-standard channels.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("plainTextContentLength", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? PlainTextContentLength { get; set; } = default!;

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fullContentKey", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FullContentKey { get; set; } = default!;

    }

    /// <summary>
    /// Represents the current delivery status of a order message.
    /// <br/>&lt;remarks&gt;
    /// <br/>When set to `SUCCESS`, the OrderFulfilledDate field is required.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FulfillmentStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"SUCCESS")]
        SUCCESS = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"IN_PROGRESS")]
        IN_PROGRESS = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"FAILURE")]
        FAILURE = 2,

    }

    /// <summary>
    /// Specifies the direction of order flow between the business and the customer.
    /// <br/>&lt;remarks&gt;
    /// <br/>From the user perspective:&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`INCOMING` - From the customer; To the user.&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`OUTGOING` - From the user; To the customer.&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum OrderFlowType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"INCOMING")]
        INCOMING = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"OUTGOING")]
        OUTGOING = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressInfo
    {
        /// <summary>
        /// The address for a party (sender or recipient) tied to the shipment order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Address { get; set; } = default!;

        /// <summary>
        /// An optional display name for a party (sender or recipient) tied to the order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Display-name format examples with Name in bold...&lt;list&gt;&lt;item&gt;&lt;description&gt;"&lt;b&gt;John Doe&lt;/b&gt;" &lt;ORD-ADDR-001&gt;&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;"&lt;b&gt;Smith, Jane (CAI - Atlanta)&lt;/b&gt;" &lt;ORD-ADDR-002&gt;&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;
        /// <br/>This value should NOT include the wrapping double quotes. Please omit them as this will be handled automatically.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

    }

    /// <summary>
    /// Response model for order content retrieval endpoint.
    /// <br/>Contains the full content of a order retrieved by encoded S3 key.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetOrderFullContentResponse
    {
        /// <summary>
        /// The primary content of the order.
        /// <br/>&lt;remarks&gt;&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`STANDARD` - standard order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIGITAL` - digital order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIRECT` - direct order content&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("content", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Content { get; set; } = default!;

    }

    /// <summary>
    /// The base order response model.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model has common order properties shared across all channel types.
    /// <br/>A discriminator field `ChannelType` correlates the polymorphic inheritance for the following.&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`STANDARD` - GetShipmentResponse&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIGITAL` - GetDigitalResponse&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
    /// </summary>
    [Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "channelType")]
    [JsonInheritanceAttribute("STANDARD", typeof(GetShipmentResponse))]
    [JsonInheritanceAttribute("DIGITAL", typeof(GetDigitalResponse))]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetOrderResponse
    {
        /// <summary>
        /// The unique identifier for the order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string OrderId { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the customer (connected customer) involved in this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string CustomerId { get; set; } = default!;

        /// <summary>
        /// The full name of the customer pertaining to this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerName { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the common user (bridge) involved in this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentId { get; set; } = default!;

        /// <summary>
        /// The full name of the common user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentName { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the common organization (store).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("storeId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string StoreId { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the (common organization) tenant.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tenantId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TenantId { get; set; } = default!;

        /// <summary>
        /// The primary content of the order truncated to first 300 visible characters.
        /// <br/>&lt;remarks&gt;
        /// <br/>Common content field between all order types.&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`STANDARD` - standard order content (with HTML removed)&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIGITAL` - digital order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIRECT` - direct order content&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderSummary", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OrderSummary { get; set; } = default!;

        /// <summary>
        /// The date and time (with offset) when the order was sent.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderPlacedDateUtc", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset OrderPlacedDateUtc { get; set; } = default!;

        /// <summary>
        /// The date and time (with offset) when the order was successfully delivered.
        /// <br/>
        /// <br/>&lt;remarks&gt;
        /// <br/>If FulfillmentStatus is set to `SUCCESS`, this field becomes required and must be provided.
        /// <br/>For other statuses, this field should be omitted or null.
        /// <br/>&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderFulfilledDateUtc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? OrderFulfilledDateUtc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("orderFlow", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OrderFlowType OrderFlow { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("merchant", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public Merchant Merchant { get; set; } = new Merchant();

        [Newtonsoft.Json.JsonProperty("platform", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Platform? Platform { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("fulfillmentStatus", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public FulfillmentStatus FulfillmentStatus { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("priority", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Priority Priority { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("orderMetadata", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OrderMetadata? OrderMetadata { get; set; } = default!;

    }

    /// <summary>
    /// The shipment order response model.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model has shipment-specific order properties.
    /// <br/>A discriminator field `ChannelType` on GetOrderResponse correlates the polymorphic inheritance.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetShipmentResponse : GetOrderResponse
    {
        /// <summary>
        /// The list of `To` recipients for the shipment order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("to", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<AddressInfo> To { get; set; } = new System.Collections.ObjectModel.Collection<AddressInfo>();

        /// <summary>
        /// The comma-delimited string of ALL `To` recipients for the shipment order.
        /// <br/>&lt;remarks&gt;
        /// <br/>If a recipient has a Name, the entry will be formatted in display-name format. Otherwise, formatted as address only.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("formattedToRecipients", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string FormattedToRecipients { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("from", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public AddressInfo From { get; set; } = new AddressInfo();

        /// <summary>
        /// The title or heading for the shipment order.
        /// <br/>&lt;remarks&gt;
        /// <br/>The order content is set using the Content field.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderTitle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OrderTitle { get; set; } = default!;

        /// <summary>
        /// List of line item metadata associated with the shipment order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lineItemInfo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<LineItemInfoResponse>? LineItemInfo { get; set; } = default!;

    }

    /// <summary>
    /// The full order response model.  Contains all order details and its full content.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetFullOrderResponse
    {
        [Newtonsoft.Json.JsonProperty("order", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public GetOrderResponse Order { get; set; } = new GetOrderResponse();

        /// <summary>
        /// The primary content of the order. Common content field between all order types.
        /// <br/>&lt;remarks&gt;&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`STANDARD` - standard order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIGITAL` - digital order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIRECT` - direct order content&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("content", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Content { get; set; } = default!;

    }

    /// <summary>
    /// The text order response model.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model has text-specific order properties.
    /// <br/>A discriminator field `ChannelType` on GetOrderResponse correlates the polymorphic inheritance.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetDigitalResponse : GetOrderResponse
    {
        [Newtonsoft.Json.JsonProperty("endpoints", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public Endpoints Endpoints { get; set; } = new Endpoints();

        /// <summary>
        /// List of attachment metadata associated with the text order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lineItemInfo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<LineItemInfoResponse>? LineItemInfo { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HttpValidationProblemDetails : ProblemDetails
    {
        [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<string>>? Errors { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PaginatedResponseOfGetOrderResponse
    {
        /// <summary>
        /// HREF pointing to the current page of results.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("href", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Href { get; set; } = default!;

        /// <summary>
        /// The total number of items for this resource. This field can be used to derive total page numbers for a given page size.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("count", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long Count { get; set; } = default!;

        /// <summary>
        /// A list of items on the current page.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<GetOrderResponse> Items { get; set; } = new System.Collections.ObjectModel.Collection<GetOrderResponse>();

        /// <summary>
        /// HREF pointing to the next page of results.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("next", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Next { get; set; } = default!;

        /// <summary>
        /// HREF pointing to the previous page of results.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("previous", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Previous { get; set; } = default!;

        /// <summary>
        /// HREF pointing to the first page of results.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("first", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? First { get; set; } = default!;

        /// <summary>
        /// The Page to be returned.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("page", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1, 2147483647)]
        public int Page { get; set; } = default!;

        /// <summary>
        /// The number of items to be returned per page.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("pageSize", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(1, 500)]
        public int PageSize { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Endpoints
    {
        /// <summary>
        /// The recipient's phone number for the text or call order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Normalized using E.164 format.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("to", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string To { get; set; } = default!;

        /// <summary>
        /// The sender's phone number for the text or call order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Normalized using E.164 format.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("from", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string From { get; set; } = default!;

    }

    /// <summary>
    /// This is the ingestion priority of the order.
    /// <br/>&lt;remarks&gt;
    /// <br/>It is currently not applicable; however, will be used to support direct full content access.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Priority
    {

        [System.Runtime.Serialization.EnumMember(Value = @"EXPRESS")]
        EXPRESS = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"STANDARD")]
        STANDARD = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProblemDetails
    {
        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Type { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("title", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Title { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Status { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("detail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Detail { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("instance", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Instance { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Contains information about the merchant and source of the order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Merchant
    {
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MerchantName Name { get; set; } = default!;

        /// <summary>
        /// The unique identifier for this order in the merchant's system.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string OrderId { get; set; } = default!;

        /// <summary>
        /// Name of the source application that initiated this order request from the Merchant.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sourceApplication", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SourceApplication { get; set; } = default!;

    }

    /// <summary>
    /// Identifies the order merchant or source system that handled the order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum MerchantName
    {

        [System.Runtime.Serialization.EnumMember(Value = @"PRIME")]
        PRIME = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FRESH")]
        FRESH = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"INTEGRATION_TEST")]
        INTEGRATION_TEST = 2,

    }

    /// <summary>
    /// Provides business context and platform (Business Unit) information related to a order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Platform
    {
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PlatformId Id { get; set; } = default!;

        /// <summary>
        /// Business Operation Identifier - the platform-specific unique instance identifier for the platform (store identifier).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("operationId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OperationId { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for the customer.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerId { get; set; } = default!;

        /// <summary>
        /// The platform-specific full name for the customer.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerName { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for the user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentId { get; set; } = default!;

        /// <summary>
        /// The platform-specific full name for the user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentName { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for an order tracking reference.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trackingId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrackingId { get; set; } = default!;

    }

    /// <summary>
    /// The unique identifier for the business platform. Required when any other Platform field is set.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PlatformId
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ORDER_DIRECT")]
        ORDER_DIRECT = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FRESH_GROCERY")]
        FRESH_GROCERY = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface, AllowMultiple = true)]
    internal class JsonInheritanceAttribute : System.Attribute
    {
        public JsonInheritanceAttribute(string key, System.Type type)
        {
            Key = key;
            Type = type;
        }

        public string Key { get; }

        public System.Type Type { get; }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public class JsonInheritanceConverter : Newtonsoft.Json.JsonConverter
    {
        internal static readonly string DefaultDiscriminatorName = "discriminator";

        private readonly string _discriminatorName;

        [System.ThreadStatic]
        private static bool _isReading;

        [System.ThreadStatic]
        private static bool _isWriting;

        public JsonInheritanceConverter()
        {
            _discriminatorName = DefaultDiscriminatorName;
        }

        public JsonInheritanceConverter(string discriminatorName)
        {
            _discriminatorName = discriminatorName;
        }

        public string DiscriminatorName { get { return _discriminatorName; } }

        public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
        {
            try
            {
                _isWriting = true;

                var jObject = Newtonsoft.Json.Linq.JObject.FromObject(value, serializer);
                jObject.AddFirst(new Newtonsoft.Json.Linq.JProperty(_discriminatorName, GetSubtypeDiscriminator(value.GetType())));
                writer.WriteToken(jObject.CreateReader());
            }
            finally
            {
                _isWriting = false;
            }
        }

        public override bool CanWrite
        {
            get
            {
                if (_isWriting)
                {
                    _isWriting = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanRead
        {
            get
            {
                if (_isReading)
                {
                    _isReading = false;
                    return false;
                }
                return true;
            }
        }

        public override bool CanConvert(System.Type objectType)
        {
            return true;
        }

        public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
        {
            var jObject = serializer.Deserialize<Newtonsoft.Json.Linq.JObject>(reader);
            if (jObject == null)
                return null;

            var discriminatorValue = jObject.GetValue(_discriminatorName);
            var discriminator = discriminatorValue != null ? Newtonsoft.Json.Linq.Extensions.Value<string>(discriminatorValue) : null;
            var subtype = GetObjectSubtype(objectType, discriminator);

            var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
            if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminatorName))
            {
                jObject.Remove(_discriminatorName);
            }

            try
            {
                _isReading = true;
                return serializer.Deserialize(jObject.CreateReader(), subtype);
            }
            finally
            {
                _isReading = false;
            }
        }

        private System.Type GetObjectSubtype(System.Type objectType, string discriminator)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Key == discriminator)
                    return attribute.Type;
            }

            return objectType;
        }

        private string GetSubtypeDiscriminator(System.Type objectType)
        {
            foreach (var attribute in System.Reflection.CustomAttributeExtensions.GetCustomAttributes<JsonInheritanceAttribute>(System.Reflection.IntrospectionExtensions.GetTypeInfo(objectType), true))
            {
                if (attribute.Type == objectType)
                    return attribute.Key;
            }

            return objectType.Name;
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HttpResponse
    {
        public int StatusCode { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public HttpResponse(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers)
        {
            StatusCode = statusCode;
            Headers = headers;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HttpResponse<TResult> : HttpResponse
    {
        public TResult Result { get; private set; }

        public HttpResponse(int statusCode, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result)
            : base(statusCode, headers)
        {
            Result = result;
        }
    }


    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderApiV1ClientException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string? Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public OrderApiV1ClientException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception? innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderApiV1ClientException<TResult> : OrderApiV1ClientException
    {
        public TResult Result { get; private set; }

        public OrderApiV1ClientException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception? innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625