//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace OrderGateway.Common.Clients.IngestExpressApi.V1
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IIngestExpressClient
    {
        /// <summary>
        /// Add a NEW digital order.
        /// </summary>
        /// <remarks>
        /// POST a valid digital order request body which responds with an Accepted new OrderId.
        /// </remarks>
        /// <returns>Accepted - Operation Successful. Order will eventually be accessible.</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> DemoAddDigitalOrderAsync(AddDigitalOrderRequest? body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Add a NEW digital order.
        /// </summary>
        /// <remarks>
        /// POST a valid digital order request body which responds with an Accepted new OrderId.
        /// </remarks>
        /// <returns>Accepted - Operation Successful. Order will eventually be accessible.</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> DemoAddDigitalOrderAsync(AddDigitalOrderRequest? body, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Add a NEW standard order.
        /// </summary>
        /// <remarks>
        /// POST a valid standard order request body which responds with an Accepted new OrderId.
        /// </remarks>
        /// <returns>Accepted - Operation Successful. Order will eventually be accessible.</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> DemoAddShipmentOrderAsync(AddShipmentOrderRequest? body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Add a NEW standard order.
        /// </summary>
        /// <remarks>
        /// POST a valid standard order request body which responds with an Accepted new OrderId.
        /// </remarks>
        /// <returns>Accepted - Operation Successful. Order will eventually be accessible.</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> DemoAddShipmentOrderAsync(AddShipmentOrderRequest? body, System.Threading.CancellationToken cancellationToken);

        /// <returns>Accepted</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> AddDigitalOrderAsync(AddDigitalOrderRequest? body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Accepted</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> AddDigitalOrderAsync(AddDigitalOrderRequest? body, System.Threading.CancellationToken cancellationToken);

        /// <returns>Accepted</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> AddShipmentOrderAsync(AddShipmentOrderRequest? body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Accepted</returns>
        /// <exception cref="OrderGatewayApiV1ClientException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<OrderResponse> AddShipmentOrderAsync(AddShipmentOrderRequest? body, System.Threading.CancellationToken cancellationToken);

    }

    /// <summary>
    /// The text order request model for the ingestion APIs.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model inherits common order properties from the base OrderRequest model.
    /// <br/>A text order requires Content.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddDigitalOrderRequest : OrderRequest
    {

        /// <summary>
        /// The recipient's phone number for the text order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Any valid (not reserved/special) phone number. See examples.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("toPhoneNumber", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ToPhoneNumber { get; set; } = default!;

        /// <summary>
        /// The sender's phone number for the text order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Any valid (not reserved/special) phone number. See examples.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fromPhoneNumber", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string FromPhoneNumber { get; set; } = default!;

    }

    /// <summary>
    /// The shipment order request model for the ingestion APIs.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model inherits common order properties from the base OrderRequest model.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddShipmentOrderRequest : OrderRequest
    {

        /// <summary>
        /// The list of `To` recipients for the shipment order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Each object in this array must contain a recipient's address.
        /// <br/>Each object in the array may optionally contain a recipient's display name.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("to", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<AddressInfo> To { get; set; } = new System.Collections.ObjectModel.Collection<AddressInfo>();

        [Newtonsoft.Json.JsonProperty("from", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public AddressInfo From { get; set; } = new AddressInfo();

        /// <summary>
        /// The title or heading for the shipment order.
        /// <br/>&lt;remarks&gt;
        /// <br/>The order body is set using the Content field.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderTitle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OrderTitle { get; set; } = default!;

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class AddressInfo
    {

        /// <summary>
        /// The address identifier for a party (sender or recipient) tied to the order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Address { get; set; } = default!;

        /// <summary>
        /// An optional display name for a party (sender or recipient) tied to the order.
        /// <br/>&lt;remarks&gt;
        /// <br/>The display name provides a human-readable label for the address identifier.
        /// <br/>Examples with `Name` in bold:&lt;list&gt;&lt;item&gt;&lt;description&gt;&lt;b&gt;John Doe&lt;/b&gt;&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;&lt;b&gt;Smith, Jane (CAI - Atlanta)&lt;/b&gt;&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;
        /// <br/>This value should NOT include wrapping double quotes. Please omit them as this will be handled automatically.&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

    }

    /// <summary>
    /// The duplicate order response model for the ingestion APIs. This is returned when an ingestion request comes in that matches an already ingested order.
    /// <br/>&lt;remarks&gt;
    /// <br/>Matches are determined by order merchant information, namely the Channel Type, Merchant's Name, and Merchant's Order ID.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class DuplicateOrderResponse
    {

        /// <summary>
        /// The unique identifier for the existing order this request was a duplicate of
        /// </summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Id { get; set; } = default!;

    }

    /// <summary>
    /// Represents the current delivery status of a order message.
    /// <br/>&lt;remarks&gt;
    /// <br/>When set to `SUCCESS`, the OrderFulfilledDate field is required.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FulfillmentStatus
    {

        [System.Runtime.Serialization.EnumMember(Value = @"SUCCESS")]
        SUCCESS = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"IN_PROGRESS")]
        IN_PROGRESS = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"FAILURE")]
        FAILURE = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class HttpValidationProblemDetails : ProblemDetails
    {

        [Newtonsoft.Json.JsonProperty("errors", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<string>>? Errors { get; set; } = default!;

    }

    /// <summary>
    /// Contains information about the merchant and source of the order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Merchant
    {

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MerchantName Name { get; set; } = default!;

        /// <summary>
        /// The unique identifier for this order in the merchant's system.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(255, MinimumLength = 1)]
        public string OrderId { get; set; } = default!;

        /// <summary>
        /// Name of the source application that initiated this order request from the Merchant.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sourceApplication", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SourceApplication { get; set; } = default!;

    }

    /// <summary>
    /// Identifies the order merchant or source system that handled the order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum MerchantName
    {

        [System.Runtime.Serialization.EnumMember(Value = @"PRIME")]
        PRIME = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FRESH")]
        FRESH = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"INTEGRATION_TEST")]
        INTEGRATION_TEST = 2,

    }

    /// <summary>
    /// Specifies the direction of order flow between the business and the customer.
    /// <br/>&lt;remarks&gt;
    /// <br/>From the user perspective:&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`INCOMING` - From the customer; To the user.&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`OUTGOING` - From the user; To the customer.&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum OrderFlowType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"INCOMING")]
        INCOMING = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"OUTGOING")]
        OUTGOING = 1,

    }

    /// <summary>
    /// The base order request model for the ingestion APIs.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model has common order properties shared across all channel types.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderRequest
    {

        /// <summary>
        /// The unique identifier for the common organization (store).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("storeId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(50, MinimumLength = 1)]
        public string StoreId { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the customer (connected customer) involved in this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(50, MinimumLength = 1)]
        public string CustomerId { get; set; } = default!;

        /// <summary>
        /// The full name of the customer pertaining to this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerName { get; set; } = default!;

        /// <summary>
        /// The unique identifier for the common user (bridge) involved in this order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentId { get; set; } = default!;

        /// <summary>
        /// The full name of the common user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentName { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("orderFlow", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OrderFlowType OrderFlow { get; set; } = default!;

        /// <summary>
        /// The primary content of the order. Common content field between all order types.
        /// <br/>&lt;remarks&gt;&lt;list type="bullet"&gt;&lt;item&gt;&lt;description&gt;`STANDARD` - standard order content&lt;/description&gt;&lt;/item&gt;&lt;item&gt;&lt;description&gt;`DIGITAL` - digital order content&lt;/description&gt;&lt;/item&gt;&lt;/list&gt;&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("content", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Content { get; set; } = default!;

        /// <summary>
        /// Optional list of Common Order Media identifiers associated with this order.
        /// <br/>&lt;remarks&gt;
        /// <br/>Maximum of 50 media IDs allowed, with each ID limited to 50 characters.
        /// <br/>&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("mediaIds", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.MaxLength(50)]
        public System.Collections.Generic.ICollection<string>? MediaIds { get; set; } = default!;

        /// <summary>
        /// The date and time (with offset) when the order was sent.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderPlacedDate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset OrderPlacedDate { get; set; } = default!;

        /// <summary>
        /// The date and time (with offset) when the order was successfully delivered.
        /// <br/>
        /// <br/>&lt;remarks&gt;
        /// <br/>If FulfillmentStatus is set to `SUCCESS`, this field becomes required and must be provided.
        /// <br/>For other statuses, this field should be omitted or null.
        /// <br/>&lt;/remarks&gt;
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orderFulfilledDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? OrderFulfilledDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("merchant", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public Merchant Merchant { get; set; } = new Merchant();

        /// <summary>
        /// The unique identifier for the (common organization) tenant.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tenantId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TenantId { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("fulfillmentStatus", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public FulfillmentStatus FulfillmentStatus { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("platform", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Platform? Platform { get; set; } = default!;

    }

    /// <summary>
    /// The order response model for the ingestion APIs.
    /// <br/>&lt;remarks&gt;
    /// <br/>This model returns the unique identifier for the order.&lt;/remarks&gt;
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderResponse
    {

        /// <summary>
        /// The unique identifier for the order.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Id { get; set; } = default!;

    }

    /// <summary>
    /// Provides business context and platform (Business Unit) information related to a order.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Platform
    {

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PlatformId Id { get; set; } = default!;

        /// <summary>
        /// Business Operation Identifier - the platform-specific unique instance identifier for the platform (store identifier).
        /// </summary>
        [Newtonsoft.Json.JsonProperty("operationId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OperationId { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for the customer.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerId { get; set; } = default!;

        /// <summary>
        /// The platform-specific full name for the customer.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("customerName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CustomerName { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for the user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentId { get; set; } = default!;

        /// <summary>
        /// The platform-specific full name for the user.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("agentName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AgentName { get; set; } = default!;

        /// <summary>
        /// The platform-specific unique identifier for tracking an order through fulfillment.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trackingId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrackingId { get; set; } = default!;

    }

    /// <summary>
    /// The unique identifier for the business platform. Required when any other Platform field is set.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PlatformId
    {

        [System.Runtime.Serialization.EnumMember(Value = @"ORDER_DIRECT")]
        ORDER_DIRECT = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FRESH_GROCERY")]
        FRESH_GROCERY = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ProblemDetails
    {

        [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Type { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("title", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Title { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? Status { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("detail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Detail { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("instance", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Instance { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object>? _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderGatewayApiV1ClientException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string? Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public OrderGatewayApiV1ClientException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception? innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class OrderGatewayApiV1ClientException<TResult> : OrderGatewayApiV1ClientException
    {
        public TResult Result { get; private set; }

        public OrderGatewayApiV1ClientException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception? innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765