<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>6e165ad4-130f-45f9-a2d8-fa856fe192eb</UserSecretsId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\OrderGateway.Common\OrderGateway.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\OrderGateway.Common\appsettings.*.json" Link="%(Filename)%(Extension)">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>